name: Java (Gradle) Release

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'

jobs:
  call-workflow:
    permissions:
      contents: write
    uses: tennessene/workflows/.github/workflows/java-gradle-release.yml@main
    secrets:
      token: ${{ secrets.TOKEN }}
      passwd: ${{ secrets.PASSWD }}
